version: "3"

services:
  db:
    image: postgres:15.1
    restart: always
    ports:
      - "9001:5432"
    volumes:
      - ./seeder/sql:/docker-entrypoint-initdb.d
    env_file:
      - .env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  seeder:
    build:
      context: ./seeder
      dockerfile: Dockerfile
    env_file:
      - ./seeder/.env
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
